export const LOGIN = "ADMIN_LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const ADD_REMINDER = "ADD_REMINDER";
export const ADD_REMINDER_ERROR = "ADD_REMINDER_ERROR";

export const GET_ALL_REMINDER = "GET_ALL_REMINDER";
export const GET_ALL_REMINDER_ERROR = "GET_ALL_REMINDER_ERROR";

export const UPDATE_REMINDER = "UPDATE_REMINDER";
export const UPDATE_REMINDER_ERROR = "UPDATE_REMINDER_ERROR";

export const DELETE_REMINDER = "DELETE_REMINDER";
export const DELETE_REMINDER_ERROR = "DELETE_REMINDER_ERROR";
